# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_keeping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='country',
            field=models.CharField(default='Canada', max_length=100),
        ),
    ]
