# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_keeping', '0003_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='authors', to='book_keeping.Author'),
        ),
    ]
