# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-29 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_keeping', '0004_auto_20170728_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='books', to='book_keeping.Author'),
        ),
    ]
