# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-03 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_keeping', '0006_auto_20170729_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='password',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='username',
            field=models.CharField(default=5, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
