# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-06 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_keeping', '0007_auto_20170803_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(default='', max_length=2)),
                ('country_name', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
