# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-07 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_keeping', '0009_auto_20170806_0335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=49, null=True)),
                ('lang_code', models.CharField(max_length=2, null=True)),
            ],
        ),
    ]
