# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-07 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_keeping', '0010_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='book_keeping.Language'),
        ),
    ]
