# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-07 23:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_keeping', '0011_book_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, null=True)),
                ('genre_type', models.CharField(choices=[('Fiction', 'Fictional Work'), ('Non-Fiction', 'Non-Fictional Work')], max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='book_keeping.Genre'),
        ),
    ]
