# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-13 05:12
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('book_keeping', '0016_auto_20170813_0444'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='author',
            managers=[
                ('genres', django.db.models.manager.Manager()),
            ],
        ),
    ]
