# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-13 05:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_keeping', '0017_auto_20170813_0512'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='author',
            managers=[
            ],
        ),
    ]
