# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-14 01:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_keeping', '0022_auto_20170814_0110'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='author',
            managers=[
            ],
        ),
    ]
